---
sudo: required

language: python

python:
  - "3.8"
services:
  - docker
env:
  - ANSIBLE="2.7"
  - ANSIBLE="2.8"
  - ANSIBLE="2.9"
cache:
  - pip
install: 
  - pip install --upgrade pip
  - pip install tox-travis
script: tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/